_wandb:
    value:
        cli_version: 0.28.1
        e:
            rj9rlh01hv9o4mg0btzs8oykd2e3jqnm:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 2
                cpu_count_logical: 4
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "244936478720"
                        used: "19129286656"
                email: stanlleylocke@gmail.com
                executable: /home/zeus/miniconda3/envs/cloudspace/bin/python
                git:
                    remote: https://github.com/stanlley-locke/project_bard.git
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-7206220e-09f8-dd01-2a94-98842fd7eb07
                host: ip-10-192-11-66
                memory:
                    total: "16554946560"
                os: Linux-6.8.0-1060-aws-x86_64-with-glibc2.39
                program: /teamspace/studios/this_studio/shakespear/project_bard/train.py
                python: CPython 3.12.11
                root: /teamspace/studios/this_studio/shakespear/project_bard
                startedAt: "2026-07-28T16:37:10.412174Z"
                writerId: rj9rlh01hv9o4mg0btzs8oykd2e3jqnm
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
                - 61
            "4": 3.12.11
            "5": 0.28.1
            "12": 0.28.1
            "13": linux-x86_64
